services:
  worker:
    container_name: cpu_rss_wacher
    build:
      context: .
      target: final
    ports:
      - 1234:1234
    restart: unless-stopped
    volumes:
      - worker-app:/app

volumes:
  worker-app: