version: "3.1"

services:

  worker:
    build:
      context: .
      target: final

    container_name: cpu_rss_wacher

    restart: unless-stopped


  prometheus:
    build:
      context: ./containers/prometheus

    container_name: prometheus

    volumes:
      - prometheus_data:/prometheus

    restart: unless-stopped


  grafana:
    build:
      context: ./containers/grafana

    container_name: grafana

    volumes:
      - grafana_data:/var/lib/grafana

    restart: unless-stopped


  web_server:
    build:
      context: ./containers/nginx

    container_name: nginx_server
    restart: unless-stopped
    ports:
      - 80:80
 

  messages_server:
    build:
      context: ./containers/nats

    container_name: nats_server

    volumes:
      - tmp_nats:/tmp/nats

    restart: unless-stopped


volumes:
  grafana_data:
  prometheus_data:
  tmp_nats:
